# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            The Tech Brew
tagline:          'Linux and Python in the Cloud'
url:              http://getpoole.com
paginate:         1
# baseurl:          http://jasonrhaas.github.io/poole/
baseurl:          /
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
